### PR TITLE
(fix): config isn't preserved after closing browser

### LINKED ISSUE #19: Ustawienia resetują się po załadowaniu wtyczki (po każdym włączeniu przeglądarki)
https://github.com/banocean/ifv/blob/main/apply.js#L92

obraz

### PR DESCRIPTION
**Pull request by Marioneq4958**
Fixes #19

### CODE REVIEW

**Review by banocean — COMMENTED** [review]
nvm

File: apply.js [hunk 1]
```diff
@@ -69,101 +69,126 @@ const patches = [
...
+      });
+    } catch (ex) {
+      reject(ex);
+    }
+  });
 };
 
-chrome.storage.sync.set({ options: config });
+async function run() {
+  let config = (await getObjectFromSyncStorage("options")) ?? {
```
Comment (banocean) [inline apply.js:93]: Is there any reason for not using this sync `chrome.storage.sync.get`?

**Review by banocean — CHANGES_REQUESTED** [review]
Looks like this will result in some issues while introducing new patches. When a new patch is added, we'd like it to be on by default

**Review by banocean — APPROVED** [review]
